remote_theme: BenKalsky/lanyon-sass
google_analytics: UA-39994406-11

# Setup
title:               Shunya Ueta
tagline:             '@hurutoriya | Computer Vision Engineer'
description:         '<a href="https://twitter.com/hurutoriya" target="_blank">@hurutoriya</a> who interesred in Computer Vision, Machine Leaning'
url:                 https://hurutoriya.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shunya Ueta (@hurutoroya)
  url:               https://twitter.com/hurutoriya
