# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shunya Ueta blog
description: Shunya Ueta Academic blog. Ride to Information Superhighway.
url: "https://hurutoroya.githu.io" # the base hostname & protocol for your site
twitter_username: hurutoriya
github_username:  hurutoriya

# Build settings
markdown: kramdown

gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
