baseURL = "https://shunyaueta.com/"
title = "Software Engineer as Data Scientist"
theme = "etch"
languageCode = "ja"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Shunya Ueta (a.k.a hurutoriya) personal website"
  copyright = "Copyright © 2013-2021 Shunya Ueta"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  page = "/:slug/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true