baseURL = "https://shunyaueta.com/"
languageCode = "ja"
title = "hurutoriya"
theme="archie"
copyright = "© Shunya Ueta"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
hasCJKLanguage = true
summaryLength = 120

[params]
	mode="auto"
	useCDN=false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/hurutoriya"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/hurutoriya/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4