baseURL = "https://shunyaueta.com/"
DefaultContentLanguage = "ja"
languageCode = "ja"
hasCJKLanguage = true

googleAnalytics = "UA-39994406-11"
disqusShortname = "hurutoriya"

title = "Shunya UETA"
theme = "ezhil"

[params]
	subtitle = "Software Engineer As Data Scientist"
  author = "hurutoriya"
  description = "Shunya UETA, a Software Engineer Machine Learning at Mercari, inc."

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/hurutoriya/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/hurutoriya"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/hurutoriya"