baseURL = "https://shunyaueta.com/"
title = "Shunya UETA"
theme ="hugo-theme-basic"
languageCode = "ja"
googleAnalytics = "UA-39994406-11"
enableEmoji = true 
copyright = "© 2016-20  <a href='https://twitter.com/hurutoriya'>@hurutoriya</a>."
description = "Shunya UETA, a Software Engineer Machine Learning at Mercari, inc."

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  twitter = "hurutoriya"

[Permalinks]
  post = "posts/:slug"

[[params.menu]]
  name = "about"
  url = "about/"
[[params.menu]]
  name = "blog"
  url = "posts/"
[[params.menu]]
  name = "tags"
  url = "tags/"